"""Constants for the pitches module."""
PITCH_COLUMN_PRIORITY: list = [
    "game_date",
    "home_team",
    "away_team",
    "pitch_type",
    "pitch_name",
    "pitcher_name",
    "batter_name",
    "release_speed",
    "release_spin_rate",
    "release_extension",
    "release_pos_x",
    "release_pos_y",
    "release_pos_z",
    "plate_x",
    "plate_z",
    "zone",
    "type",
    "description",
    "events",
    "balls",
    "strikes",
    "outs_when_up",
    "inning",
    "inning_topbot",
    "stand",
    "p_throws",
    "launch_speed",
    "launch_angle",
    "hit_distance_sc",
]

HIDDEN_PITCH_COLUMNS: tuple = {"pitcher", "batter"}
